### ISSUE TITLE
Assignment 01 -- 21 Feb 2024

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2023-2#1]
+ Create GitHub account and report you link to your user profile here. (Point: 20)
+ Create a Medium account, write a story containing your reason in taking this course, and report link to the story here. (Point: 40)
+ Create a Jupyter Notebook, share it as gist, and report the link to the gist here. (Point: 40)

Read the information on https://edunex.itb.ac.id/courses/58272/preview/234923

**Comment by halserach** [comment]
Name: Christopher / 20223014

1. My Github account: https://github.com/halserach
2. My article about my reason of taking this course: https://medium.com/@christopher.wiguna/modern-physicists-are-data-analysts-this-is-why-an-opinion-f1b757b3324c
3. My gist (from an old assignment): https://gist.github.com/halserach/ca093c5db9bbc0ad325e0b8741fd2580

Thank you very much!

(note: because my personal preference to use Linux, I use Ubuntu WSL and config the python, its virtual environment, pip, and many more libraries there instead. Is it okay to do that in this course?)

**Comment by gitaameliiaa** [comment]
Name : Gita Amelia Marianto Limbong
Student ID : 10220018

1. Github account: https://github.com/gitaameliiaa
2. Medium article about reason in taking this course: https://medium.com/@gitaameliamarianto26/data-processing-is-a-key-f29834604095
3. Link to the gist: https://gist.github.com/gitaameliiaa/24bcddb4e3e53acb4dba0b6f1a8ced56

**Comment by Andikaprtm02** [comment]
Name: Andika Pratama / 20223002

1. Github account: https://github.com/Andikaprtm02
2. Why I choose this course, in my medium account: https://medium.com/@andikaprtm02/data-processing-holds-significant-importance-in-todays-world-yes-i-can-273d637789fa
3. My new gist: https://gist.github.com/Andikaprtm02/abe291b3386006915cdf18ce4a051f2b (I am still learning using this)

**Comment by denikaryono** [comment]
Deni Kartika / 20223004

1. Github account: https://github.com/denikaryono
2. Medium story: https://medium.com/@denikaryono/computational-physics-and-what-it-can-do-5f4e94cb3e84
3. My gist: https://gist.github.com/denikaryono/951232d2e05cd94f15b0d9fa10b45dc8

**Comment by albabalfinur** [comment]
Alfi Nur Albab/20223012
1. Github account: https://github.com/albabalfinur
2. Medium story: https://medium.com/@albabalfinur/data-processing-as-a-tool-to-refine-mobile-robot-duty-ac5fab016cd9
3. Gist: https://gist.github.com/albabalfinur/2a8e938c910d09ad4c2b4f679c1d14b2
